name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.6.2'
        host: 'windows'
        target: 'win64_msvc2019_64'

    - name: Setup MSVC Environment
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '17.6'

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release --parallel

    - name: Package Application
      run: |
        mkdir release
        xcopy /E /I /Y build\Release\* release\
        xcopy /E /I /Y build\Release\where\* release\qml

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release
        asset_name: MyApp-${{ github.ref_name }}.zip
        asset_content_type: application/zip